 export type WineCardType = {
  id: number;
  name: string;
  varietal: string;
  mainImage: string;
  price: string;
  bottleVolume: number;
  description: string;
  year: string;
  wineryName: string;
  acidityName: number;
  fizzinessValue: number;
  sweetnessValue: number;
  tanninValue: number;
  quantityInStock: number;
  isDeleted: boolean;
  styleId: number;
  typeId: number;
  regionId: number;
  acidityValue:number;
  alcohol: number;
  grapes: null;
  images: string[];
  intensityValue: number;
  meals: null;
  regions: null;
  type: string;
  wineStyle: object;
  wineType: object;
}
